[package]
name = "ble-to-mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = { version = "0.10", features = ["serde"] }
serde = "1.0.154"
serde_json = "1.0.94"
serde_with = "2.3.0"
rand = "0.8.5"
uuid = "1.3.0"
tokio = { version = "1.26.0", features = ["full"] }
futures = "0.3.26"
envconfig = "0.10.0"
rumqttc = "0.20.0"
hex = "0.4.3"
anyhow = "1.0.69"
log = "0.4.17"
chrono = "0.4.23"
env_logger = "0.10.0"
