name: Release

on:
  workflow_dispatch:
  release:
    branches: [ master ]
    types: [ published ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        target: [ x86_64-unknown-linux-musl, x86_64-pc-windows-gnu, aarch64-apple-darwin ]
        target: [ x86_64-unknown-linux-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.68
          target: ${{ matrix.target }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install cross
        shell: bash
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Build target
        shell: bash
        run: |
          cross build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release          
          tar czf ../../../${{ github.event.repository.name }}-${{ matrix.target }}.tar.gz ${{ github.event.repository.name }}
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: '${{ github.event.repository.name }}-*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

