name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

    steps:
    - uses: actions/checkout@v3

    - name: "Install dependencies"
      run: sudo apt update && sudo apt install -y libdbus-1-dev pkg-config

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.68

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test --verbose
