name: Rust

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Install dependencies"
      run: sudo apt update && sudo apt install -y libdbus-1-dev pkg-config

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.72

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test --verbose
